version: "3.8"

services:
  streamlit-app:
    build: .
    container_name: streamlit_qrcode
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
